TARGET = wireless_tx
LOCAL_LIBS = ../include

include ../Env.mk
include ../Arduino.mk

TEST_MAC = $(lib)/$(lib)/dan
PAT = yep

debug: 
	echo $(OBJS)
	echo $(SYS_OBJS)
	echo $(SYS_OBJ_DIRS)
	echo $(SYS_CPP_SRCS,cpp=c)
	echo $(foreach lib, a b c, $(TEST_MAC))
	@echo here: $(filter %e%, yep group nopeyepnote)
